<?php

namespace Acme\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbRow() {
        return $this->createQueryBuilder("user")
            ->select('COUNT(user)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
